apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: frontend
    visualize: true
    uses: dispatcher
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: frontend
        visualize: true
                uses: dispatcher
        visualize: "true"
>>>>>>>> Alias
    spec:
      containers:
      - image: gcr.io/multimicro-1129/frontend
        name: frontend
        env:
          - name: DISPATCHER
            value: "dispatcher"

        ports:
        - containerPort: 8080
          name: http-server
