apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: frontend
  name: frontend-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - image: gcr.io/multimicro-1129/frontend
        name: frontend
        env:
          - name: DISPATCHER
            value: "dispatcher"

        ports:
        - containerPort: 8080
          name: http-server
