apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dispatcher
    visualize: "true"
  name: dispatcher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dispatcher
        visualize: "true"
        uses: renderer
    spec:
      containers:
      - image: gcr.io/multimicro-1129/dispatcher
        name: dispatcher
        env:
          - name: RENDERER
            value: "renderer"
        ports:
        - containerPort: 50051
          name: dispatcher
