apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dispatcher
    visualize: true
    uses: renderer
  name: dispatcher-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: dispatcher
    spec:
      containers:
      - image: gcr.io/multimicro/dispatcher
        name: dispatcher
        env:
          - name: RENDERER
          value: "renderer"
        ports:
        - containerPort: 50051
          name: dispatcher
